var age = 15;
//console.log(typeof age);
var limit = 30;
limit = 45;
limit = "dara";
console.log(typeof limit);
console.log(limit);
var y = undefined;
var z = null;
console.log(typeof y);
console.log(typeof z);
